{% set name = "immuneML" %}
  {% set version = "3.0.3" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/i/{{ name|lower }}/{{ name|lower }}-{{ version }}.tar.gz"
  sha256: e8bb82c987ebdc8960cae3c8441b495741916f7ad0ec59e9b0fd3d1c59711240


build:
  number: 1
  entry_points:
    - immune-ml = immuneML.app.ImmuneMLApp:main
    - immune-ml-quickstart = immuneML.workflows.instructions.quickstart:main
  script:
    - echo 'Installing pip dependencies...'
    - "{{ PYTHON }} -m pip install --no-cache-dir fisher fishersapi stitchr imgtgenedl || exit 1"
    - echo 'Installing immuneML...'
    - "{{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vvv || exit 1"

  run_exports:
    - {{ pin_subpackage('immuneml', max_pin="x") }}

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - pip
    - python
    - cython
  run:
requirements:
requirements:
  build:
    - python >=3.11,<3.12
    - pip
  host:
    - fisher
    - fishersapi
    - stitchr
    - imgtgenedl
  run:
    - python >=3.11,<3.12
    - fisher
    - stitchr
    - imgtgenedl
    - airr >=1,<1.6
    - dill >=0.3
    - editdistance >=0.6,<0.7  # Compatible with Python >=3.10,<3.12
    - fishersapi
    - gensim >=3.8,<4
    - h5py >=2.9.0
    - logomaker >=0.8
    - matplotlib-base >=3.1
    - matplotlib-venn >=0.11
    - numpy >=1.18,<2.0
    - pandas >=1,<3
    - plotly >=4
    - pystache ==0.5.4
    - pytest >=6,<8  # Compatible with Python >=3.10
    - pytorch >=1.5.1
    - python >=3.10,<3.12
    - pyyaml >=5.3
    - regex >=2024.9,<2025.0
    - requests >=2.22,<2.33  # Compatible with urllib3 versions
    - scikit-learn >=0.23,<1.2
    - scipy >=1.5,<1.14
    - tensorboard >=1.14.0
    - tqdm >=4.11,<5  # Compatible with Python >=3.10
    - tzlocal >=2,<4

test:
  imports:
    - immuneML  # Check if the immuneML module can be imported


about:
  home: "https://github.com/uio-bmi/immuneML"
  license: APGL-3.0-only
  license_family: AGPL
  license_file: LICENSE.md
  summary: "immuneML is a software platform for machine learning analysis of immune receptor repertoires."
  doc_url: "https://docs.immuneml.uio.no/"
  dev_url: "https://github.com/uio-bmi/immuneML"

extra:
  skip-lints:
    - cython_must_be_in_host
  recipe-maintainers:
    - knutwa-ext
    - BlueBasilisk
    - pavlovicmilena
